@startuml
'https://plantuml.com/class-diagram

abstract class DatosPersonales {
- calle: String
- ciudad: String
- telefono: int
- email: String
}

class Facultad {
- profesores: List<Profesor>
- alumnos: List<Alumno>
- materias: List<Materia>
+ addMateria(materia: Materia)
+ addCorrelativa(materia: Materia, correlativa: Materia)
+ addAlumno(alumno: Alumno)
+ addProfesor(profesor: Profesor)
+ addMateriaProfesor(profesor: Profesor, materia: Materia)
+ addMateriaAlumno(alumno: Alumno, materia: Materia)
+ materiasDeProfesor(profesor: Profesor) : List<Profesor>
+ cantidadAlumnosMateria(materia: Materia): int
+ cantidadAlumnosPorMateria(): Map<Materia, Integer>
}

class Alumno {
- legajo: int
- nombre: String
- apellido: String
- materias: List<Materia>
# addMateria(materia: Materia)
}

class Profesor{
- legajo: int
- nombre: String
- apellido: String
- materias: List<Materia>
# addMateria(materia: Materia)
}

DatosPersonales <-- Alumno
DatosPersonales <-- Profesor
Facultad --> Alumno
Facultad -> Profesor

@enduml